---

- name: "Remove hash from modprobe"
  shell: rm -f /etc/modprobe.d/illumio.conf
  when: "prefix_name in group_names"

- name: "Remove conntrack from sysctl"
  shell: rm -f /etc/sysctl.d/illumio.conf
  when: "prefix_name in group_names"

- name: "Remove firewalld rules"
  shell: rm -f /etc/firewalld/zones/illumio.xml
  when: "prefix_name in group_names"

- name: "Remove firewalld rules"
  shell: rm -f /etc/firewalld/zones/illumio.xml.old
  when: "prefix_name in group_names"

- name: Restore original state of firewalld.conf if LogDenied was updated
  shell: sed -i'Backup' 's/LogDenied=all/LogDenied=off/' /etc/firewalld/firewalld.conf

- name: Remove /etc/rsyslog.d/firewalld-dropped.conf file
  file:
    path: /etc/rsyslog.d/firewalld-dropped.conf
    state: absent

- name: Restart rsyslog service if /etc/rsyslog.d/firewalld-dropped.conf was removed
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: "Prevent firewalld from getting loaded"
  systemd:
    name: firewalld
    state: stopped
    enabled: no
    masked: no
  ignore_errors: true
  when: "prefix_name in group_names"
