---

- name: "Stopping PCE"
  command: illumio-pce-ctl stop
  become: true
  become_user: ilo-pce
  ignore_errors: true
  when: "prefix_name in group_names"


- name: "Uninstall the UI RPM"
  dnf:
    name: illumio-pce-ui
    state: absent
  when: "prefix_name in group_names and 'corenodes' in group_names"


- name: "Uninstall the PCE RPM"
  dnf:
    name: illumio-pce
    state: absent
  when: "prefix_name in group_names"


- name: "Clean up directories"
  file:
    path: "{{item}}"
    state: absent
  with_items:
   - /var/lib/illumio-pce/
   - /var/log/illumio-pce/
   - /etc/illumio-pce
   - /opt/illumio-pce
  when: "prefix_name in group_names"
  ignore_errors: true
  retries: 5

- name: "Copy Backup /etc/hosts"
  command: cp /etc/hosts.bak /etc/hosts
  when: "prefix_name in group_names"
  ignore_errors: true

- name: Revert Kernel Parameters Configuration on Core Nodes
  file:
    path: /etc/sysctl.d/99-illumio.conf
    state: absent
  when: "'corenodes' in group_names"

- name: Revert Kernel Parameters Configuration on Data Nodes
  file:
    path: /etc/sysctl.d/99-illumio.conf
    state: absent
  when: "'datanodes' in group_names"

- name: Revert Conntrack Hashsize Configuration
  file:
    path: /etc/modprobe.d/illumio.conf
    state: absent
  when: "'corenodes' in group_names"

- name: Revert Illumio limits
  file:
    path: /etc/systemd/system/illumio-pce.service.d/override.conf
    state: absent
  when: "prefix_name in group_names"
