{
    "pce_rpm_software" : "${pce_software}",
    "pce_ui_rpm_software" : "${pce_ui_software}",
    "install_root" : "/opt/illumio-pce",
    "runtime_data_dir" : "/var/lib/illumio-pce/tmp",
    "persistent_data_dir" : "/var/lib/illumio-pce/data",
    "ephemeral_data_dir" : "/var/lib/illumio-pce/tmp",
    "log_dir" : "/var/log/illumio-pce",
    "private_key_cache_dir" : "/var/lib/illumio-pce/keys",
    "cert_dir" : "/var/lib/illumio-pce/cert",
    "root_ca_cert" : "${root_ca_file}",
    "machine_cert" : "${certificate_file}",
    "machine_private_key" : "${certificate_passwd}",
    "data_dir": "${data_dir}",
    "service_discovery_server" : "${sds}",
    "service_discovery_encryption_key" : "${sde_key}",
    "pce_fqdn_name" : "${pce_fqdn}",
    "load_balancer_ip" : "${lb_vip}",
    "prefix_name" : "pce",
    "pce_domain_name" : "${pce_domain_name}",
    "pce_ui_username" : "${pce_admin_user}",
    "pce_ui_fullname" : "${pce_admin_fullname}",
    "pce_ui_password" : "${pce_admin_passwd}",
    "ansible_ssh_user": "${ansible_ssh_user}",
    "org_name" : "${org_name}",
    "ven_port" : "${front_end_port}",
    "ven_lightning_port" : "${front_end_svc_port}",
    "mgmt_port" : "${front_end_port}",
    "backup_location" : "/tmp",
    "ansible_password" : "${ansible_password}",
    "ansible_sudo_pass" : "${ansible_sudo_password}",
        "ansible_become_password" : "${ansible_sudo_password}",
    "desired_locale" : "en_US.UTF-8",
    "create_lb" : "${create_lb}",
    "keepalived_auth" : "${keepalived_auth}",
    "set_hostname": {
        "lb_vip": ${jsonencode(set_hostname.lb_vip)},
        "pce_lb_nodes": ${jsonencode(set_hostname.pce_lb_nodes)},
        "pce_core_nodes": ${jsonencode(set_hostname.pce_core_nodes)},
        "pce_data_nodes": ${jsonencode(set_hostname.pce_data_nodes)}
      }
}
