---
- name: Run fips-mode-setup --check
  command: fips-mode-setup --check
  register: fips_check_result
  changed_when: false
  ignore_errors: true
  when: "prefix_name in group_names"

- name: Disable FIPS mode if enabled
  command: fips-mode-setup --disable
  when: "'FIPS mode is disabled.' not in fips_check_result.stdout"
  register: disable_fips
  changed_when: disable_fips.rc == 0
  ignore_errors: true

- name: Reboot if FIPS mode was disabled
  reboot:
    reboot_timeout: 600
  when: disable_fips.changed
  async: 0
  poll: 0
  become: yes
  ignore_errors: false

- name: Set Hostname for LB VIP
  set_fact:
    new_hostname: "{{ set_hostname.lb_vip.host_name }}"
  when: inventory_hostname == set_hostname.lb_vip.ip_address

- name: Execute command to set hostname for LB VIP
  command: hostnamectl set-hostname "{{ new_hostname }}"
  when: inventory_hostname == set_hostname.lb_vip.ip_address

- name: Set Hostnames for LB Nodes
  command: hostnamectl set-hostname "{{ item.key }}"
  with_items: "{{ set_hostname.pce_lb_nodes | dict2items }}"
  when: inventory_hostname == item.value

- name: Set Hostnames for Core Nodes
  command: hostnamectl set-hostname "{{ item.key }}"
  with_items: "{{ set_hostname.pce_core_nodes | dict2items }}"
  when: inventory_hostname == item.value

- name: Set Hostnames for Data Nodes
  command: hostnamectl set-hostname "{{ item.key }}"
  with_items: "{{ set_hostname.pce_data_nodes | dict2items }}"
  when: inventory_hostname == item.value


- name: "Backup original /etc/hosts"
  command: cp /etc/hosts /etc/hosts.bak
  when: "prefix_name in group_names"
  ignore_errors: true

- name: "Copy Hosts file to each Hosts"
  copy:
    src: "{{ playbook_dir }}/../../working/hosts.txt"
    dest: /etc/hosts
  when: "prefix_name in group_names"
  ignore_errors: true

- name: "Check for and install dependencies"
  yum:
    state: present
    name: ["coreutils","findutils","net-tools","procps","gawk","grep","util-linux-ng","sed","sudo","glibc","libgcc","libstdc++","ncurses-libs","zlib"]
  when: "prefix_name in group_names"


- name: "Install tools and required packages"
  yum:
      state: present
      name: ["postfix","logrotate","net-tools"]
  when: "prefix_name in group_names"
  retries: 5

- name: Download EPEL GPG 8 key.
  get_url:
    url: https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8
  retries: 5
  when: "prefix_name in group_names and ansible_distribution_major_version|int == 8"

- name: Download EPEL GPG 9 key.
  get_url:
    url: https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
    dest: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-9
  retries: 5
  when: "prefix_name in group_names and ansible_distribution_major_version|int == 9"

- name: Import EPEL GPG-8 key.
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8
    state: present
  retries: 5
  when: "prefix_name in group_names and ansible_distribution_major_version|int == 8"

- name: Import EPEL GPG-9 key.
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-9
    state: present
  retries: 5
  when: "prefix_name in group_names and ansible_distribution_major_version|int == 9"


- name: Install EPEL repo.
  retries: 5
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    state: present

- name: "Stop iptables service"
  service:
    name: iptables
    state: stopped
    enabled: false
  ignore_errors: True
  when: "prefix_name in group_names"

- name: "Start firewalld service"
  service:
    name: firewalld
    state: started
    enabled: false
  ignore_errors: True
  when: "prefix_name in group_names"

- name: "Configure Alias File"
  blockinfile:
      dest: /etc/profile.d/global_aliases.sh
      create: yes
      block: |
        # Illumio-specific aliases and functions
        alias pce_env_check="sudo -u ilo-pce /opt/illumio-pce/illumio-pce-env check"
        alias pce_ctl="sudo -u ilo-pce /opt/illumio-pce/illumio-pce-ctl"
        alias pce_db="sudo -u ilo-pce /opt/illumio-pce/illumio-pce-db-management"
  when: "prefix_name in group_names"


- name: "Copy bundle to /etc/pki/ca-trust/source/anchors/"
  copy:
      src: "{{ playbook_dir }}/../../certs/{{ root_ca_cert }}"
      dest: /etc/pki/ca-trust/source/anchors/
      mode: 0400
  when: "prefix_name in group_names and root_ca_cert != ''"
  ignore_errors: true

- name: "update-ca-trust force-enable"
  command: update-ca-trust force-enable
  when: "prefix_name in group_names and root_ca_cert != ''"

- name: "update-ca-trust extract"
  command: update-ca-trust extract
  when: "prefix_name in group_names and root_ca_cert != ''"

- name: "Remove Root CA"
  command: "rm -f /etc/pki/ca-trust/source/anchors/{{ root_ca_cert }}"
  when: "prefix_name in group_names and root_ca_cert != ''"
  ignore_errors: true
